### PR TITLE
Use a better tempdir, fix some documentation, and make json test more readable

### PR DESCRIPTION
**Pull request by karenetheridge**
I found a directory being left behind called /tmp/HTTP-Entity-Parser-MultiPart-TVRlb, which another process can find and try to read.

### CODE REVIEW

**Comment by kazeburo** [comment]
Thank you karenetheridge.
Could you remove JSON::MaybeXS from dependencies?
Because Plack dependencies should be in pure perl. see https://github.com/plack/Plack/wiki/Release-management

JSON::MaybeXS depends Cpanel::JSON::XS.

**Comment by shadowcat-mst** [comment]
@kazeburo This is wrong, JSON::MaybeXS was explicitly designed to be fatpackable - and will fall back to JSON::PP to do so. I designed it to work that way.

**Comment by karenetheridge** [comment]
Indeed, JSON::MaybeXS's Makefile.PL checks to see if XS is possible, and if not, only depends on JSON::PP.

**Comment by karenetheridge** [comment]
I'll do a JSON::MaybeXS release later today that clarifies this in the documentation, and keeps the ::XS modules out of META.json (even though there is dynamic_config=>1, this listing could cause confusion, as it's what metacpan.org shows in the dependency list.)

**Comment by kazeburo** [comment]
OK
I missed `dynamic_config => 1`.

**Comment by kazeburo** [comment]
I just have released HTTP::Entity::Parser 0.18 to CPAN.

**Comment by karenetheridge** [comment]
Awesome, thanks!

(and today's release of JSON::MaybeXS fixes up the prereq list that metacpan displays, and has a bit more documentation about the dynamic prereqs.)

**Pull request merged**
